CREATE TABLE CUSTOMER (CUSTOMER_ID NUMBER(19) NOT NULL, NAME VARCHAR2(255) NULL, PRIMARY KEY (CUSTOMER_ID));
CREATE TABLE ADDRESS (CUSTOMER_ID NUMBER(19) NOT NULL, CITY VARCHAR2(255) NULL, COUNTRY VARCHAR2(255) NULL, PRIMARY KEY (CUSTOMER_ID));

ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES ADDRESS (CUSTOMER_ID);
ALTER TABLE ADDRESS ADD CONSTRAINT FK_ADDRESS_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

CREATE TABLE SEQUENCE_TABLE (SEQ_NAME VARCHAR2(50) NOT NULL, SEQ_COUNT NUMBER(38) NULL, PRIMARY KEY (SEQ_NAME));

INSERT INTO SEQUENCE_TABLE(SEQ_NAME, SEQ_COUNT) values ('CUSTOMER', 0);

CREATE SEQUENCE HIBERNATE_SEQUENCE MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE ;