CREATE TABLE PERSON (PERSON_ID int, NAME VARCHAR(15) NULL, PASS_ID int  NULL UNIQUE, PRIMARY KEY (PERSON_ID));




CREATE TABLE PASSPORT (PASSPORT_ID int NOT NULL, PASSPORT_NO VARCHAR(15) NULL, PRIMARY KEY (PASSPORT_ID));



LTER TABLE PERSON ADD CONSTRAINT FK_PERSON_PASS_ID FOREIGN KEY (PASS_ID) REFERENCES PASSPORT (PASSPORT_ID);
CREATE TABLE SEQUENCE_TABLE (SEQ_NAME VARCHAR2(50) NOT NULL, SEQ_COUNT NUMBER(38) NULL, PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE_TABLE(SEQ_NAME, SEQ_COUNT) values ('PERSON', 0);
INSERT INTO SEQUENCE_TABLE(SEQ_NAME, SEQ_COUNT) values ('PASSPORT', 0);

