ALTER TABLE PERSON DROP CONSTRAINT FK_PERSON_PASS_ID;
DROP TABLE PERSON;
DROP TABLE PASSPORT;
DELETE FROM SEQUENCE_TABLE WHERE SEQ_NAME = 'PERSON';
DELETE FROM SEQUENCE_TABLE WHERE SEQ_NAME = 'PASSPORT';
